### ISSUE TITLE
Did someone delete the project in the Firebase Console?

### ISSUE THREAD

**Issue by noidwasavailable** [noidwasavailable/burstmybubble#19]
I just got an email from Firebase saying that our project was upgraded to pay-as-you-go, so I went to the console to delete the project, then I saw someone already deleted it. Did one of y'all delete it lol? Thanks!

![image](https://github.com/noidwasavailable/burstmybubble/assets/26755327/1e6d7ca2-ae31-44aa-95c4-67f80782d626)

**Comment by mickowale** [comment]
Hey! Yeah I deleted the assigned API. Hopefully, our users wont mind :)

**Comment by noidwasavailable** [comment]
Nice! Thanks for the fast action! Hope you're doing well :D
